[package]
authors = ["Matthias Endler <matthias-endler.de>"]
description = "A boring link checker for my projects (and maybe yours)"
documentation = "https://github.com/hello-rust/lychee/blob/master/README.md"
edition = "2018"
homepage = "https://github.com/hello-rust/lychee"
license = "Apache-2.0/MIT"
name = "lychee"
repository = "https://github.com/hello-rust/lychee"
version = "0.1.0"

[dependencies]
github-rs = "0.7.0"
pico-args = "0.3.3"
pulldown-cmark = "0.7.2"
regex = "1.3.9"
serde_json = "1.0.56"
url = "2.1.1"
log = "0.4"
pretty_env_logger = "0.4"

[dependencies.reqwest]
version = "0.10.7"
features = ["blocking", "gzip"]
