[package]
name = "lychee"
version = "0.1.0"
authors = ["Matthias Endler <matthias-endler.de>"]
edition = "2018"

[dependencies]
github-rs = "0.7.0"
serde_json = "1.0.56"
regex = "1.3.9"
reqwest = { version = "0.10", features = ["blocking"] }
pulldown-cmark = "0.7.2"
pico-args = "0.3.3"
