[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[[example]]
name = "builder"
path = "builder.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib", version = "0.13.0" }
tokio = { version = "1.28.1", features = ["full"] }
regex = "1.8.3"
http = "0.2.9"
reqwest = { version = "0.11.18", features = ["gzip"] }
